spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youth_study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      # 跟新或者创建数据表结构
      ddl-auto: update
    #控制台显示sql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: db/base/create.sql


